#! /bin/bash

### BEGIN INIT INFO
# Provides: tightvnc
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VNC Server at boot time
# Description: Start VNC Server at boot time.
### END INIT INFO

# /etc/init.d/tightvnc

USER=kali
HOME=/home/kali

DISPNO=1       # Display No
WIDTH=1280     # Display geometry widht
HEIGHT=800     # Display geometry height
DEPTH=24       # Use color depth

OPTIONS=":${DISPNO} -geometry ${WIDTH}x${HEIGHT} -depth ${DEPTH}"

export USER HOME

case "$1" in
    start)
        echo "Starting TightVNC Server"
        #Insert your favoured settings for a TightVNC session
        su $USER -c "/usr/bin/tightvncserver ${OPTIONS}"
        ;;

    stop)
        echo "Stopping VNC Server"
        su $USER -c "/usr/bin/tightvncserver -kill :$DISPNO"
        ;;

    *)
        echo "Usage: /etc/init.d/tightvnc {start|stop}"
        exit 1
        ;;
esac

exit 0
